// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render } from '@testing-library/react';
import App from '../../App.js';
import { MemoryRouter, Route } from 'react-router-dom';

describe('App Routing', () => {
  test('default path should render the Birthday component', () => {
    const { getByTestId } = render(
      <MemoryRouter initialEntries={['/']}>
        <App />
      </MemoryRouter>
    );
    expect(getByTestId('birthday-component')).toBeInTheDocument();
  });

  test('"/birthday/:name/:day/:month" path should render the RouterBirthday component with parameters', () => {
    const { getByTestId } = render(
      <MemoryRouter initialEntries={['/birthday/john/21/04']}>
        <App />
      </MemoryRouter>
    );
    expect(getByTestId('router-birthday-component')).toBeInTheDocument();
    expect(getByTestId('name-param')).toHaveTextContent('john');
    expect(getByTestId('day-param')).toHaveTextContent('21');
    expect(getByTestId('month-param')).toHaveTextContent('04');
  });

  test('"/generate" path should render the Generate component', () => {
    const { getByTestId } = render(
      <MemoryRouter initialEntries={['/generate']}>
        <App />
      </MemoryRouter>
    );
    expect(getByTestId('generate-component')).toBeInTheDocument();
  });
});

