// ********RoostGPT********
// Test generated by RoostGPT for test react-tic using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// src/__tests__/src/Wish.test.jsx
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Wish from '../../Wish.jsx'; // Import statement considering the position of this file and Wish.jsx

describe('Wish component', () => {
  test('renders correctly with given name', () => {
    render(<Wish name="John" />);
    expect(screen.getByText(/happy birthday john/i)).toBeInTheDocument();
  });

  test('displays name in uppercase', () => {
    render(<Wish name="Jane" />);
    const nameElement = screen.getByText(/jane/i);
    expect(nameElement).toHaveClass('highlight');
    expect(nameElement).toHaveTextContent('JANE');
  });

  test('does not render without name prop', () => {
    const { container } = render(<Wish />);
    expect(container).toBeEmptyDOMElement();
  });

  // Further tests can include edge cases or behavior under different prop values
});

