// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
/**
 * __tests__/src/App.test.js
 */

// Importing necessary utilities and components
import React from 'react';
import { render, screen } from '@testing-library/react';
import { BrowserRouter as Router } from 'react-router-dom';
import App from '../../src/App.js';

// Mocking the other components since we do not have their implementation details
jest.mock('../../src/Birthday.js', () => () => <div data-testid="Birthday">Birthday Component</div>);
jest.mock('../../src/RouterBirthday.js', () => () => <div data-testid="RouterBirthday">RouterBirthday Component</div>);
jest.mock('../../src/Generate.js', () => () => <div data-testid="Generate">Generate Component</div>);

describe('App component routes', () => {
  test('renders the Birthday component on the root route', () => {
    render(
      <Router>
        <App />
      </Router>
    );
    expect(screen.getByTestId('Birthday')).toBeInTheDocument();
  });

  test('renders the RouterBirthday component on the /birthday/:name?/:day?/:month? route', () => {
    window.history.pushState({}, 'RouterBirthday Test', '/birthday/john/1/1');
    render(
      <Router>
        <App />
      </Router>
    );
    expect(screen.getByTestId('RouterBirthday')).toBeInTheDocument();
  });

  test('renders the Generate component on the /generate route', () => {
    window.history.pushState({}, 'Generate Test', '/generate');
    render(
      <Router>
        <App />
      </Router>
    );
    expect(screen.getByTestId('Generate')).toBeInTheDocument();
  });
});

