// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// Jest unit test for src/Birthday.jsx
// Relative path from __tests__/src to src/Birthday.jsx is ../src/Birthday.jsx

import React from 'react';
import { render, cleanup } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Birthday from '../src/Birthday.jsx';

// Mocking Countdown component as it's used within Birthday component
jest.mock('../src/Countdown.jsx', () => () => <div data-testid="countdown-mock"></div>);

describe('Birthday Component', () => {
  afterEach(cleanup);

  test('renders with default props when none are provided', () => {
    // Render component without props
    const { getByText } = render(<Birthday />);
    expect(getByText(/deepankar/i)).toBeInTheDocument();
    expect(getByTestId('countdown-mock')).toBeInTheDocument();
  });

  test('renders correctly with given props', () => {
    // Render component with props
    const { getByText } = render(<Birthday name="Alice" day={5} month={1} />);
    expect(getByText(/alice/i)).toBeInTheDocument();
  });

  // Additional test cases can be added here to test different scenarios
});

