// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// src/__tests__/Countdown.test.js

import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Countdown from '../Countdown';

describe('Countdown Component', () => {
  test('renders countdown when it is not the birthday', () => {
    const countdownData = {
      isItBday: false,
      days: 5,
      hours: 3,
      minutes: 30,
      seconds: 15,
    };
    const name = 'John';

    render(<Countdown countdownData={countdownData} name={name} />);
    const daysElement = screen.getByText('5');
    expect(daysElement).toHaveTextContent('Days');
    const hoursElement = screen.getByText('3');
    expect(hoursElement).toHaveTextContent('Hours');
  });

  test('renders Wish component when it is the birthday', () => {
    const countdownData = { isItBday: true };
    const name = 'John';

    render(<Countdown countdownData={countdownData} name={name} />);
    const wishElement = screen.getByText(/happy birthday/i);
    expect(wishElement).toBeInTheDocument();
  });

  // Additional test cases can be added here to cover more scenarios
});

