// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import Birthday from './Birthday';

const RouterBirthday = (props) => {
  const { params } = props.match;
  const { name, day, month } = params;
  return (
    <>
      <Birthday name={name} month={month} day={day} />
    </>
  );
};

export default RouterBirthday;

