// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// __tests__/src/Wish.test.js
import React from 'react';
import { render, screen } from '@testing-library/react';
import Wish from 'src/Wish.jsx'; // Import path adjusted based on the test directory

describe('Wish component', () => {
  test('renders correctly with a name', () => {
    render(<Wish name="John" />);
    const wishElement = screen.getByText(/happy birthday john !!!/i);
    expect(wishElement).toBeInTheDocument();
    expect(wishElement).toHaveClass('wish-message');
    const highlightElement = screen.getByText('JOHN');
    expect(highlightElement).toHaveClass('highlight');
  });

  test('renders uppercase name', () => {
    render(<Wish name="Jane" />);
    const highlightElement = screen.getByText('JANE');
    expect(highlightElement).toHaveClass('highlight');
  });

  test('handles empty name prop', () => {
    render(<Wish name="" />);
    const wishElement = screen.getByText(/happy birthday !!!/i);
    expect(wishElement).toBeInTheDocument();
    // Optionally, check that the 'highlight' class is not present or is empty
  });

  // Additional tests can go here, for example:
  // - Testing component with default props if they are specified
  // - Error boundary testing if the component handles errors
});


