// ********RoostGPT********
// Test generated by RoostGPT for test react-bday using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import Wish from '../../src/Wish.jsx'; // Relative path from __tests__/src to src/Wish.jsx

describe('Wish component', () => {
  // Test case for rendering with a name
  test('renders a birthday wish with the given name in uppercase', () => {
    const name = 'John';
    render(<Wish name={name} />);
    const wishMessageElement = screen.getByText(`HAPPY BIRTHDAY ${name.toUpperCase()} !!!`, { exact: false });
    expect(wishMessageElement).toBeInTheDocument();
  });

  // Test case for rendering without a name
  test('does not display a name if none is provided', () => {
    render(<Wish />);
    const wishMessageElement = screen.getByText('HAPPY BIRTHDAY', { exact: false });
    expect(wishMessageElement).toBeInTheDocument();
    expect(wishMessageElement).not.toHaveTextContent('undefined');
  });

  // You could add more test cases here according to your criteria
});


